// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clone": {
            "post": {
                "description": "Clone a Git repository from GitHub, GitLab, or Bitbucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "git"
                ],
                "summary": "Clone a repository",
                "parameters": [
                    {
                        "description": "Clone Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CloneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get the health status of the API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HealthResponse"
                        }
                    }
                }
            }
        },
        "/prcomment": {
            "post": {
                "description": "Add a comment to a specific line in a pull/merge request from GitHub, GitLab, or Bitbucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "git"
                ],
                "summary": "Add a comment to a pull/merge request",
                "parameters": [
                    {
                        "description": "PR Comment Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PRCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prdiff": {
            "get": {
                "description": "Get the diff for a pull/merge request from GitHub, GitLab, or Bitbucket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "git"
                ],
                "summary": "Get pull/merge request diff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider (github, gitlab, bitbucket)",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pull/Merge Request URL",
                        "name": "pr_url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authentication token",
                        "name": "token",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Username for authentication",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Password for authentication",
                        "name": "password",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CloneRequest": {
            "type": "object",
            "required": [
                "destination",
                "provider",
                "url"
            ],
            "properties": {
                "branch": {
                    "type": "string",
                    "example": "main"
                },
                "destination": {
                    "type": "string",
                    "example": "./repo"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "github",
                        "gitlab",
                        "bitbucket"
                    ],
                    "example": "github"
                },
                "ssh_key_path": {
                    "type": "string",
                    "example": "~/.ssh/id_rsa"
                },
                "token": {
                    "type": "string",
                    "example": "ghp_xxxxxxxxxxxx"
                },
                "url": {
                    "type": "string",
                    "example": "https://github.com/user/repo.git"
                },
                "username": {
                    "type": "string",
                    "example": "username"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request parameters"
                }
            }
        },
        "models.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "models.PRCommentRequest": {
            "type": "object",
            "required": [
                "comment",
                "file_path",
                "line_number",
                "pr_url",
                "provider"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "This looks good!"
                },
                "file_path": {
                    "type": "string",
                    "example": "src/main.go"
                },
                "line_number": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 42
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "pr_url": {
                    "type": "string",
                    "example": "https://github.com/user/repo/pull/123"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "github",
                        "gitlab",
                        "bitbucket"
                    ],
                    "example": "github"
                },
                "token": {
                    "type": "string",
                    "example": "ghp_xxxxxxxxxxxx"
                },
                "username": {
                    "type": "string",
                    "example": "username"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string",
                    "example": "An error occurred"
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
